// Code generated by entc, DO NOT EDIT.

package annotation

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/sut63/team01/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Messages applies equality check predicate on the "messages" field. It's identical to MessagesEQ.
func Messages(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMessages), v))
	})
}

// MessagesEQ applies the EQ predicate on the "messages" field.
func MessagesEQ(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMessages), v))
	})
}

// MessagesNEQ applies the NEQ predicate on the "messages" field.
func MessagesNEQ(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMessages), v))
	})
}

// MessagesIn applies the In predicate on the "messages" field.
func MessagesIn(vs ...string) predicate.Annotation {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Annotation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMessages), v...))
	})
}

// MessagesNotIn applies the NotIn predicate on the "messages" field.
func MessagesNotIn(vs ...string) predicate.Annotation {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Annotation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMessages), v...))
	})
}

// MessagesGT applies the GT predicate on the "messages" field.
func MessagesGT(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMessages), v))
	})
}

// MessagesGTE applies the GTE predicate on the "messages" field.
func MessagesGTE(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMessages), v))
	})
}

// MessagesLT applies the LT predicate on the "messages" field.
func MessagesLT(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMessages), v))
	})
}

// MessagesLTE applies the LTE predicate on the "messages" field.
func MessagesLTE(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMessages), v))
	})
}

// MessagesContains applies the Contains predicate on the "messages" field.
func MessagesContains(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMessages), v))
	})
}

// MessagesHasPrefix applies the HasPrefix predicate on the "messages" field.
func MessagesHasPrefix(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMessages), v))
	})
}

// MessagesHasSuffix applies the HasSuffix predicate on the "messages" field.
func MessagesHasSuffix(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMessages), v))
	})
}

// MessagesEqualFold applies the EqualFold predicate on the "messages" field.
func MessagesEqualFold(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMessages), v))
	})
}

// MessagesContainsFold applies the ContainsFold predicate on the "messages" field.
func MessagesContainsFold(v string) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMessages), v))
	})
}

// HasDispensemedicine applies the HasEdge predicate on the "dispensemedicine" edge.
func HasDispensemedicine() predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DispensemedicineTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DispensemedicineTable, DispensemedicineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDispensemedicineWith applies the HasEdge predicate on the "dispensemedicine" edge with a given conditions (other predicates).
func HasDispensemedicineWith(preds ...predicate.DispenseMedicine) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DispensemedicineInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DispensemedicineTable, DispensemedicineColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Annotation) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Annotation) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Annotation) predicate.Annotation {
	return predicate.Annotation(func(s *sql.Selector) {
		p(s.Not())
	})
}
