// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team01/ent/medicine"
	"github.com/sut63/team01/ent/medicinetype"
	"github.com/sut63/team01/ent/predicate"
)

// MedicineTypeUpdate is the builder for updating MedicineType entities.
type MedicineTypeUpdate struct {
	config
	hooks      []Hook
	mutation   *MedicineTypeMutation
	predicates []predicate.MedicineType
}

// Where adds a new predicate for the builder.
func (mtu *MedicineTypeUpdate) Where(ps ...predicate.MedicineType) *MedicineTypeUpdate {
	mtu.predicates = append(mtu.predicates, ps...)
	return mtu
}

// SetName sets the name field.
func (mtu *MedicineTypeUpdate) SetName(s string) *MedicineTypeUpdate {
	mtu.mutation.SetName(s)
	return mtu
}

// AddMedicineIDs adds the Medicine edge to Medicine by ids.
func (mtu *MedicineTypeUpdate) AddMedicineIDs(ids ...int) *MedicineTypeUpdate {
	mtu.mutation.AddMedicineIDs(ids...)
	return mtu
}

// AddMedicine adds the Medicine edges to Medicine.
func (mtu *MedicineTypeUpdate) AddMedicine(m ...*Medicine) *MedicineTypeUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mtu.AddMedicineIDs(ids...)
}

// Mutation returns the MedicineTypeMutation object of the builder.
func (mtu *MedicineTypeUpdate) Mutation() *MedicineTypeMutation {
	return mtu.mutation
}

// RemoveMedicineIDs removes the Medicine edge to Medicine by ids.
func (mtu *MedicineTypeUpdate) RemoveMedicineIDs(ids ...int) *MedicineTypeUpdate {
	mtu.mutation.RemoveMedicineIDs(ids...)
	return mtu
}

// RemoveMedicine removes Medicine edges to Medicine.
func (mtu *MedicineTypeUpdate) RemoveMedicine(m ...*Medicine) *MedicineTypeUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mtu.RemoveMedicineIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mtu *MedicineTypeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(mtu.hooks) == 0 {
		affected, err = mtu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicineTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mtu.mutation = mutation
			affected, err = mtu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mtu.hooks) - 1; i >= 0; i-- {
			mut = mtu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mtu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mtu *MedicineTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := mtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mtu *MedicineTypeUpdate) Exec(ctx context.Context) error {
	_, err := mtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtu *MedicineTypeUpdate) ExecX(ctx context.Context) {
	if err := mtu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mtu *MedicineTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicinetype.Table,
			Columns: medicinetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicinetype.FieldID,
			},
		},
	}
	if ps := mtu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicinetype.FieldName,
		})
	}
	if nodes := mtu.mutation.RemovedMedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicinetype.MedicineTable,
			Columns: []string{medicinetype.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtu.mutation.MedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicinetype.MedicineTable,
			Columns: []string{medicinetype.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicinetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MedicineTypeUpdateOne is the builder for updating a single MedicineType entity.
type MedicineTypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *MedicineTypeMutation
}

// SetName sets the name field.
func (mtuo *MedicineTypeUpdateOne) SetName(s string) *MedicineTypeUpdateOne {
	mtuo.mutation.SetName(s)
	return mtuo
}

// AddMedicineIDs adds the Medicine edge to Medicine by ids.
func (mtuo *MedicineTypeUpdateOne) AddMedicineIDs(ids ...int) *MedicineTypeUpdateOne {
	mtuo.mutation.AddMedicineIDs(ids...)
	return mtuo
}

// AddMedicine adds the Medicine edges to Medicine.
func (mtuo *MedicineTypeUpdateOne) AddMedicine(m ...*Medicine) *MedicineTypeUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mtuo.AddMedicineIDs(ids...)
}

// Mutation returns the MedicineTypeMutation object of the builder.
func (mtuo *MedicineTypeUpdateOne) Mutation() *MedicineTypeMutation {
	return mtuo.mutation
}

// RemoveMedicineIDs removes the Medicine edge to Medicine by ids.
func (mtuo *MedicineTypeUpdateOne) RemoveMedicineIDs(ids ...int) *MedicineTypeUpdateOne {
	mtuo.mutation.RemoveMedicineIDs(ids...)
	return mtuo
}

// RemoveMedicine removes Medicine edges to Medicine.
func (mtuo *MedicineTypeUpdateOne) RemoveMedicine(m ...*Medicine) *MedicineTypeUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mtuo.RemoveMedicineIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (mtuo *MedicineTypeUpdateOne) Save(ctx context.Context) (*MedicineType, error) {

	var (
		err  error
		node *MedicineType
	)
	if len(mtuo.hooks) == 0 {
		node, err = mtuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicineTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mtuo.mutation = mutation
			node, err = mtuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mtuo.hooks) - 1; i >= 0; i-- {
			mut = mtuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mtuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (mtuo *MedicineTypeUpdateOne) SaveX(ctx context.Context) *MedicineType {
	mt, err := mtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return mt
}

// Exec executes the query on the entity.
func (mtuo *MedicineTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := mtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuo *MedicineTypeUpdateOne) ExecX(ctx context.Context) {
	if err := mtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mtuo *MedicineTypeUpdateOne) sqlSave(ctx context.Context) (mt *MedicineType, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicinetype.Table,
			Columns: medicinetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicinetype.FieldID,
			},
		},
	}
	id, ok := mtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing MedicineType.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := mtuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicinetype.FieldName,
		})
	}
	if nodes := mtuo.mutation.RemovedMedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicinetype.MedicineTable,
			Columns: []string{medicinetype.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtuo.mutation.MedicineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicinetype.MedicineTable,
			Columns: []string{medicinetype.MedicineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	mt = &MedicineType{config: mtuo.config}
	_spec.Assign = mt.assignValues
	_spec.ScanValues = mt.scanValues()
	if err = sqlgraph.UpdateNode(ctx, mtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicinetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return mt, nil
}
