/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDispenseMedicine
 */
export interface ControllersDispenseMedicine {
    /**
     * 
     * @type {number}
     * @memberof ControllersDispenseMedicine
     */
    amountchangemedicine?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDispenseMedicine
     */
    annotation?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDispenseMedicine
     */
    datetime?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersDispenseMedicine
     */
    detailchangemedicine?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersDispenseMedicine
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDispenseMedicine
     */
    pharmacist?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDispenseMedicine
     */
    prescription?: number;
}

export function ControllersDispenseMedicineFromJSON(json: any): ControllersDispenseMedicine {
    return ControllersDispenseMedicineFromJSONTyped(json, false);
}

export function ControllersDispenseMedicineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDispenseMedicine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountchangemedicine': !exists(json, 'amountchangemedicine') ? undefined : json['amountchangemedicine'],
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'datetime': !exists(json, 'datetime') ? undefined : json['datetime'],
        'detailchangemedicine': !exists(json, 'detailchangemedicine') ? undefined : json['detailchangemedicine'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'pharmacist': !exists(json, 'pharmacist') ? undefined : json['pharmacist'],
        'prescription': !exists(json, 'prescription') ? undefined : json['prescription'],
    };
}

export function ControllersDispenseMedicineToJSON(value?: ControllersDispenseMedicine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amountchangemedicine': value.amountchangemedicine,
        'annotation': value.annotation,
        'datetime': value.datetime,
        'detailchangemedicine': value.detailchangemedicine,
        'note': value.note,
        'pharmacist': value.pharmacist,
        'prescription': value.prescription,
    };
}


