/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersMedicine
 */
export interface ControllersMedicine {
    /**
     * 
     * @type {number}
     * @memberof ControllersMedicine
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersMedicine
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersMedicine
     */
    howtouse?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersMedicine
     */
    levelOfDangerousID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersMedicine
     */
    medicineTypeID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersMedicine
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersMedicine
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersMedicine
     */
    serial?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersMedicine
     */
    unitOfMedicineID?: number;
}

export function ControllersMedicineFromJSON(json: any): ControllersMedicine {
    return ControllersMedicineFromJSONTyped(json, false);
}

export function ControllersMedicineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersMedicine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'howtouse': !exists(json, 'howtouse') ? undefined : json['howtouse'],
        'levelOfDangerousID': !exists(json, 'levelOfDangerousID') ? undefined : json['levelOfDangerousID'],
        'medicineTypeID': !exists(json, 'medicineTypeID') ? undefined : json['medicineTypeID'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'serial': !exists(json, 'serial') ? undefined : json['serial'],
        'unitOfMedicineID': !exists(json, 'unitOfMedicineID') ? undefined : json['unitOfMedicineID'],
    };
}

export function ControllersMedicineToJSON(value?: ControllersMedicine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'brand': value.brand,
        'howtouse': value.howtouse,
        'levelOfDangerousID': value.levelOfDangerousID,
        'medicineTypeID': value.medicineTypeID,
        'name': value.name,
        'price': value.price,
        'serial': value.serial,
        'unitOfMedicineID': value.unitOfMedicineID,
    };
}


