/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersOrder
 */
export interface ControllersOrder {
    /**
     * 
     * @type {string}
     * @memberof ControllersOrder
     */
    addedtime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    companyid?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersOrder
     */
    hospitalid?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    medicineid?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    pharmacistid?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersOrder
     */
    price?: number;
}

export function ControllersOrderFromJSON(json: any): ControllersOrder {
    return ControllersOrderFromJSONTyped(json, false);
}

export function ControllersOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedtime': !exists(json, 'addedtime') ? undefined : json['addedtime'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'companyid': !exists(json, 'companyid') ? undefined : json['companyid'],
        'hospitalid': !exists(json, 'hospitalid') ? undefined : json['hospitalid'],
        'medicineid': !exists(json, 'medicineid') ? undefined : json['medicineid'],
        'pharmacistid': !exists(json, 'pharmacistid') ? undefined : json['pharmacistid'],
        'price': !exists(json, 'price') ? undefined : json['price'],
    };
}

export function ControllersOrderToJSON(value?: ControllersOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedtime': value.addedtime,
        'amount': value.amount,
        'companyid': value.companyid,
        'hospitalid': value.hospitalid,
        'medicineid': value.medicineid,
        'pharmacistid': value.pharmacistid,
        'price': value.price,
    };
}


