/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBill
 */
export interface ControllersBill {
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBill
     */
    annotation?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    dispenseMedicine?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    payments?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    pharmacists?: number;
}

export function ControllersBillFromJSON(json: any): ControllersBill {
    return ControllersBillFromJSONTyped(json, false);
}

export function ControllersBillFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'dispenseMedicine': !exists(json, 'dispenseMedicine') ? undefined : json['dispenseMedicine'],
        'payments': !exists(json, 'payments') ? undefined : json['payments'],
        'pharmacists': !exists(json, 'pharmacists') ? undefined : json['pharmacists'],
    };
}

export function ControllersBillToJSON(value?: ControllersBill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'annotation': value.annotation,
        'dispenseMedicine': value.dispenseMedicine,
        'payments': value.payments,
        'pharmacists': value.pharmacists,
    };
}


