/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPrescription
 */
export interface ControllersPrescription {
    /**
     * 
     * @type {string}
     * @memberof ControllersPrescription
     */
    annotation?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    doctorID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    medicineID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    patientInfoID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    statusID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPrescription
     */
    symptom?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPrescription
     */
    value?: string;
}

export function ControllersPrescriptionFromJSON(json: any): ControllersPrescription {
    return ControllersPrescriptionFromJSONTyped(json, false);
}

export function ControllersPrescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPrescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'doctorID': !exists(json, 'doctorID') ? undefined : json['doctorID'],
        'medicineID': !exists(json, 'medicineID') ? undefined : json['medicineID'],
        'patientInfoID': !exists(json, 'patientInfoID') ? undefined : json['patientInfoID'],
        'statusID': !exists(json, 'statusID') ? undefined : json['statusID'],
        'symptom': !exists(json, 'symptom') ? undefined : json['symptom'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ControllersPrescriptionToJSON(value?: ControllersPrescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'annotation': value.annotation,
        'doctorID': value.doctorID,
        'medicineID': value.medicineID,
        'patientInfoID': value.patientInfoID,
        'statusID': value.statusID,
        'symptom': value.symptom,
        'value': value.value,
    };
}


