/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAnnotation,
    EntAnnotationFromJSON,
    EntAnnotationFromJSONTyped,
    EntAnnotationToJSON,
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntPharmacist,
    EntPharmacistFromJSON,
    EntPharmacistFromJSONTyped,
    EntPharmacistToJSON,
    EntPrescription,
    EntPrescriptionFromJSON,
    EntPrescriptionFromJSONTyped,
    EntPrescriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDispenseMedicineEdges
 */
export interface EntDispenseMedicineEdges {
    /**
     * 
     * @type {EntAnnotation}
     * @memberof EntDispenseMedicineEdges
     */
    annotation?: EntAnnotation;
    /**
     * 
     * @type {EntBill}
     * @memberof EntDispenseMedicineEdges
     */
    bills?: EntBill;
    /**
     * 
     * @type {EntPharmacist}
     * @memberof EntDispenseMedicineEdges
     */
    pharmacist?: EntPharmacist;
    /**
     * 
     * @type {EntPrescription}
     * @memberof EntDispenseMedicineEdges
     */
    prescription?: EntPrescription;
}

export function EntDispenseMedicineEdgesFromJSON(json: any): EntDispenseMedicineEdges {
    return EntDispenseMedicineEdgesFromJSONTyped(json, false);
}

export function EntDispenseMedicineEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDispenseMedicineEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'annotation': !exists(json, 'Annotation') ? undefined : EntAnnotationFromJSON(json['Annotation']),
        'bills': !exists(json, 'Bills') ? undefined : EntBillFromJSON(json['Bills']),
        'pharmacist': !exists(json, 'Bharmacist') ? undefined : EntPharmacistFromJSON(json['Pharmacist']),
        'prescription': !exists(json, 'Prescription') ? undefined : EntPrescriptionFromJSON(json['Prescription']),
    };
}

export function EntDispenseMedicineEdgesToJSON(value?: EntDispenseMedicineEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'annotation': EntAnnotationToJSON(value.annotation),
        'bills': EntBillToJSON(value.bills),
        'pharmacist': EntPharmacistToJSON(value.pharmacist),
        'prescription': EntPrescriptionToJSON(value.prescription),
    };
}


