/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCompany,
    EntCompanyFromJSON,
    EntCompanyFromJSONTyped,
    EntCompanyToJSON,
    EntMedicine,
    EntMedicineFromJSON,
    EntMedicineFromJSONTyped,
    EntMedicineToJSON,
    EntPharmacist,
    EntPharmacistFromJSON,
    EntPharmacistFromJSONTyped,
    EntPharmacistToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOrderEdges
 */
export interface EntOrderEdges {
    /**
     * 
     * @type {EntCompany}
     * @memberof EntOrderEdges
     */
    company?: EntCompany;
    /**
     * 
     * @type {EntMedicine}
     * @memberof EntOrderEdges
     */
    medicine?: EntMedicine;
    /**
     * 
     * @type {EntPharmacist}
     * @memberof EntOrderEdges
     */
    pharmacist?: EntPharmacist;
}

export function EntOrderEdgesFromJSON(json: any): EntOrderEdges {
    return EntOrderEdgesFromJSONTyped(json, false);
}

export function EntOrderEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOrderEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'company': !exists(json, 'company') ? undefined : EntCompanyFromJSON(json['company']),
        'medicine': !exists(json, 'medicine') ? undefined : EntMedicineFromJSON(json['medicine']),
        'pharmacist': !exists(json, 'pharmacist') ? undefined : EntPharmacistFromJSON(json['pharmacist']),
    };
}

export function EntOrderEdgesToJSON(value?: EntOrderEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': EntCompanyToJSON(value.company),
        'medicine': EntMedicineToJSON(value.medicine),
        'pharmacist': EntPharmacistToJSON(value.pharmacist),
    };
}


