/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntDispenseMedicine,
    EntDispenseMedicineFromJSON,
    EntDispenseMedicineFromJSONTyped,
    EntDispenseMedicineToJSON,
    EntDrugAllergy,
    EntDrugAllergyFromJSON,
    EntDrugAllergyFromJSONTyped,
    EntDrugAllergyToJSON,
    EntOrder,
    EntOrderFromJSON,
    EntOrderFromJSONTyped,
    EntOrderToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPharmacistEdges
 */
export interface EntPharmacistEdges {
    /**
     * Bills holds the value of the Bills edge.
     * @type {Array<EntBill>}
     * @memberof EntPharmacistEdges
     */
    bills?: Array<EntBill>;
    /**
     * Dispensemedicine holds the value of the dispensemedicine edge.
     * @type {Array<EntDispenseMedicine>}
     * @memberof EntPharmacistEdges
     */
    dispensemedicine?: Array<EntDispenseMedicine>;
    /**
     * Drugallergys holds the value of the drugallergys edge.
     * @type {Array<EntDrugAllergy>}
     * @memberof EntPharmacistEdges
     */
    drugallergys?: Array<EntDrugAllergy>;
    /**
     * Order holds the value of the order edge.
     * @type {Array<EntOrder>}
     * @memberof EntPharmacistEdges
     */
    order?: Array<EntOrder>;
}

export function EntPharmacistEdgesFromJSON(json: any): EntPharmacistEdges {
    return EntPharmacistEdgesFromJSONTyped(json, false);
}

export function EntPharmacistEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPharmacistEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bills': !exists(json, 'bills') ? undefined : ((json['bills'] as Array<any>).map(EntBillFromJSON)),
        'dispensemedicine': !exists(json, 'dispensemedicine') ? undefined : ((json['dispensemedicine'] as Array<any>).map(EntDispenseMedicineFromJSON)),
        'drugallergys': !exists(json, 'drugallergys') ? undefined : ((json['drugallergys'] as Array<any>).map(EntDrugAllergyFromJSON)),
        'order': !exists(json, 'order') ? undefined : ((json['order'] as Array<any>).map(EntOrderFromJSON)),
    };
}

export function EntPharmacistEdgesToJSON(value?: EntPharmacistEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bills': value.bills === undefined ? undefined : ((value.bills as Array<any>).map(EntBillToJSON)),
        'dispensemedicine': value.dispensemedicine === undefined ? undefined : ((value.dispensemedicine as Array<any>).map(EntDispenseMedicineToJSON)),
        'drugallergys': value.drugallergys === undefined ? undefined : ((value.drugallergys as Array<any>).map(EntDrugAllergyToJSON)),
        'order': value.order === undefined ? undefined : ((value.order as Array<any>).map(EntOrderToJSON)),
    };
}


