/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMedicine,
    EntMedicineFromJSON,
    EntMedicineFromJSONTyped,
    EntMedicineToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUnitOfMedicineEdges
 */
export interface EntUnitOfMedicineEdges {
    /**
     * Medicine holds the value of the Medicine edge.
     * @type {Array<EntMedicine>}
     * @memberof EntUnitOfMedicineEdges
     */
    medicine?: Array<EntMedicine>;
}

export function EntUnitOfMedicineEdgesFromJSON(json: any): EntUnitOfMedicineEdges {
    return EntUnitOfMedicineEdgesFromJSONTyped(json, false);
}

export function EntUnitOfMedicineEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUnitOfMedicineEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicine': !exists(json, 'Medicine') ? undefined : ((json['Medicine'] as Array<any>).map(EntMedicineFromJSON)),
    };
}

export function EntUnitOfMedicineEdgesToJSON(value?: EntUnitOfMedicineEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medicine': value.medicine === undefined ? undefined : ((value.medicine as Array<any>).map(EntMedicineToJSON)),
    };
}


